flowchart TD
    A[google.com] -->|DNS| B(https://142.251.211.206:443)
    B --> C("Encryption")
    C --> D("SSL")
    C --> E("HTTPS")
    B --> F("Security")
    F --> G("Firewall on Google's server")
    F --> H("Firewall on Load Balancer")
    B --> I("Load Balancer")
    I --> J("Server 1 (10ms) ❌")
    I --> K("Server 2 (20ms) ❌")
    I --> L("Server 3 (5ms) ✅")
    B --> M("GET https://142.251.211.206:443")
    M --> N("Web Server")
    N --> O("index.html")
    N --> P("favicon.png")
    N --> Q("script.js")
    N --> R("style.css")
    N --> S("...")
    M --> T("TCP/IP")
    M --> U("Application Server")
    U --> V("Account login check")
    U --> W("User settings")
    U --> X("Location")
    M --> Y("Database requests")
    Y --> Z("Search")
    Y --> Aa("Search History")
    Y --> Ab("Gemini conversations")
